export async function seed(knex) {
  await knex('comics').del()
  await knex('comics').insert([
    {
      id: 1,
      title: 'The Last Ronin: Wish for Death.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'One',
      datePublished: '2020-10-28',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Peter Laird, Tom Waltz',
      coverArt: '',
      coverArtist:
        'Esau Escorza, Issac Escorza, Kevin Eastman, Mateus Santolouco',
    },
    {
      id: 2,
      title: 'The Last Ronin: First to Fall.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'Two',
      datePublished: '2021-02-17',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Peter Laird, Tom Waltz',
      coverArt: '',
      coverArtist:
        'Esau Escorza, Issac Escorza, Kevin Eastman, Mateus Santolouco',
    },
    {
      id: 3,
      title: 'The Last Ronin: Fight or Flight.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'Three',
      datePublished: '2021-05-26',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Peter Laird, Tom Waltz',
      coverArt: '',
      coverArtist:
        'Esau Escorza, Issac Escorza, Kevin Eastman, Mateus Santolouco',
    },
    {
      id: 4,
      title: 'The Last Ronin: Blood in Snow.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'Four',
      datePublished: '2021-09-22',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Peter Laird, Tom Waltz',
      coverArt: '',
      coverArtist: 'Esau Escorza, Issac Escorza, Dave Wachter',
    },
    {
      id: 5,
      title: 'The Last Ronin: The Last Ronin.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'Five',
      datePublished: '2022-04-27',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Peter Laird, Tom Waltz',
      coverArt: '',
      coverArtist: 'Esau Escorza, Issac Escorza, Ben Bishop, Kevin Eastman',
    },
    {
      id: 6,
      title: 'Gargoyles: Here in Manhattan.',
      name: 'Disney',
      issue: '#01',
      datePublished: '2022-08',
      publisher: 'Dynamite Entertainment',
      credits: 'Greg Weisman, George Kambadais',
      coverArt: '',
      coverArtist: 'David Nakayama',
    },
    {
      id: 7,
      title: 'Gargoyles',
      name: 'Disney',
      issue: '#02',
      datePublished: '2022-09',
      publisher: 'Dynamite Entertainment',
      credits: 'Greg Weisman, George Kambadais',
      coverArt: '',
      coverArtist: 'David Nakayama',
    },
    {
      id: 8,
      title: 'Gargoyles',
      name: 'Disney',
      issue: '#03',
      datePublished: '2022-10',
      publisher: 'Dynamite Entertainment',
      credits: 'Greg Weisman, George Kambadais',
      coverArt: '',
      coverArtist: 'David Nakayama',
    },
    {
      id: 9,
      title: 'Gargoyles',
      name: 'Disney',
      issue: '#04',
      datePublished: '2022-11',
      publisher: 'Dynamite Entertainment',
      credits: 'Greg Weisman, George Kambadais',
      coverArt: '',
      coverArtist: 'David Nakayama',
    },
    {
      id: 10,
      title: 'Gargoyles',
      name: 'Disney',
      issue: '#05',
      datePublished: '2022-12',
      publisher: 'Dynamite Entertainment',
      credits: 'Greg Weisman, George Kambadais',
      coverArt: '',
      coverArtist: 'David Nakayama',
    },
  ])
}
