export async function seed(knex) {
  await knex('comics').del()
  await knex('comics').insert([
    {
      id: 1,
      title: 'The Last Ronin: Wish for Death.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'One',
      datePublished: '28-10-2020',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Peter Laird, Tom Waltz',
      coverArt: '/images/TMNT-TLR-1.jpg',
      coverArtist:
        'Esau Escorza, Issac Escorza, Kevin Eastman, Mateus Santolouco',
    },
    {
      id: 2,
      title: 'The Last Ronin: First to Fall.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'Two',
      datePublished: '17-02-2021',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Peter Laird, Tom Waltz',
      coverArt: '/images/TMNT-TLR-2.jpg',
      coverArtist:
        'Esau Escorza, Issac Escorza, Kevin Eastman, Mateus Santolouco',
    },
    {
      id: 3,
      title: 'The Last Ronin: Fight or Flight.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'Three',
      datePublished: '26-05-2021',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Peter Laird, Tom Waltz',
      coverArt: '/images/TMNT-TLR-3.jpg',
      coverArtist:
        'Esau Escorza, Issac Escorza, Kevin Eastman, Mateus Santolouco',
    },
    {
      id: 4,
      title: 'The Last Ronin: Blood in Snow.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'Four',
      datePublished: '22-09-2021',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Peter Laird, Tom Waltz',
      coverArt: '/images/TMNT-TLR-4.jpg',
      coverArtist: 'Esau Escorza, Issac Escorza, Dave Wachter',
    },
    {
      id: 5,
      title: 'The Last Ronin: The Last Ronin.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'Five',
      datePublished: '27-04-2022',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Peter Laird, Tom Waltz',
      coverArt: '/images/TMNT-TLR-5.jpg',
      coverArtist: 'Esau Escorza, Issac Escorza, Ben Bishop, Kevin Eastman',
    },
    {
      id: 6,
      title: 'Gargoyles: Here in Manhattan.',
      name: 'Disney',
      issue: '#01',
      datePublished: '08-2022',
      publisher: 'Dynamite Entertainment',
      credits: 'Greg Weisman, George Kambadais',
      coverArt: '/images/gargoyles-1.jpg',
      coverArtist: 'David Nakayama',
    },
    {
      id: 7,
      title: 'Gargoyles',
      name: 'Disney',
      issue: '#02',
      datePublished: '09-2022',
      publisher: 'Dynamite Entertainment',
      credits: 'Greg Weisman, George Kambadais',
      coverArt: '/images/gargoyles-2.jpg',
      coverArtist: 'David Nakayama',
    },
    {
      id: 8,
      title: 'Gargoyles: Three',
      name: 'Disney',
      issue: '#03',
      datePublished: '10-2022',
      publisher: 'Dynamite Entertainment',
      credits: 'Greg Weisman, George Kambadais',
      coverArt: '/images/gargoyles-3.jpg',
      coverArtist: 'David Nakayama',
    },
    {
      id: 9,
      title: 'Gargoyles: Four',
      name: 'Disney',
      issue: '#04',
      datePublished: '11-2022',
      publisher: 'Dynamite Entertainment',
      credits: 'Greg Weisman, George Kambadais',
      coverArt: '/images/gargoyles-4.jpg',
      coverArtist: 'David Nakayama',
    },
    {
      id: 10,
      title: 'Gargoyles: Five',
      name: 'Disney',
      issue: '#05',
      datePublished: '12-2022',
      publisher: 'Dynamite Entertainment',
      credits: 'Greg Weisman, George Kambadais',
      coverArt: '/images/gargoyles-5.jpg',
      coverArtist: 'David Nakayama',
    },
    {
      id: 11,
      title: 'The Last Ronin: Lost Years.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'One',
      datePublished: '25-01-2023',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Tom Waltz',
      coverArt: '/images/TMNT-LY-1.jpg',
      coverArtist: 'Ben Bishop, Kevin Eastman, SL Gallant',
    },
    {
      id: 12,
      title: 'The Last Ronin: Lost Years.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'Two',
      datePublished: '15-03-2023',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Tom Waltz',
      coverArt: '/images/TMNT-LY-2.jpg',
      coverArtist: 'Ben Bishop',
    },
    {
      id: 13,
      title: 'The Last Ronin: Lost Years.',
      name: 'Teenage Mutant Ninja Turtles',
      issue: 'One',
      datePublished: '26-04-2023',
      publisher: 'IDW Publishing',
      credits: 'Kevin Eastman, Tom Waltz',
      coverArt: '/images/TMNT-LY-3.jpg',
      coverArtist: 'Kevin Eastman, Ben Bishop',
    },
  ])
}
